# Generated by Django 4.1.5 on 2023-02-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('New_image', models.FileField(default=None, max_length=250, null=True, upload_to='new/')),
            ],
        ),
    ]
