# Generated by Django 4.1.5 on 2023-02-02 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Img',
        ),
    ]
